INSERT INTO USER (NAME, SURNAME, IS_PROCESSED, CREATION_DATE ) VALUES ('Alejandra','Jaramillo', false, {ts '2021-02-02'});
INSERT INTO USER (NAME, SURNAME, IS_PROCESSED, CREATION_DATE ) VALUES ('Nidia','Cobos', false, {ts '2021-02-02'});
INSERT INTO USER (NAME, SURNAME, IS_PROCESSED, CREATION_DATE ) VALUES ('Joaquin','Cabrera', false, {ts '2021-02-02'});